### PR TITLE
Remove all tests

### PR DESCRIPTION
**Pull request by Koeng101**
v1.17.0, v1.16.0, v1.15.0, v1.14.1, v1.14.0, v1.13.0, v1.11.0, v1.10.1, v1.9.0, v1.8.1, v1.6.1, and v1.5.3 all have completely failing tests (or about 3 months of development). That code has got to be depreciated at this point, so this pr removes it all!

Cheers!

### CODE REVIEW

**Comment by kennyworkman** [comment]
yeah thats uh actually quite fair

**Comment by kennyworkman** [comment]
we'll use this pr to correct tests

**Comment by kennyworkman** [comment]
removed the offending logic for regsitration on master, @ayushkamat is working on a new framework for testing pieces of the sdk that involve creating and pushing containers, else all else is in order

**Comment by Koeng101** [comment]
Beautiful green checkmark! Wonderful!

**Pull request closed without merging**
